name: image-processing-tools
channels:
  - pytorch
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - asn1crypto=0.24.0=py37_0
  - astroid=2.1.0=py37_0
  - babel=2.6.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py37_0
  - cffi=1.11.5=py37h74b6da3_1
  - chardet=3.0.4=py37_1
  - cloudpickle=0.7.0=py_0
  - colorama=0.4.1=py37_0
  - cryptography=2.5=py37h7a1dbc1_0
  - cycler=0.10.0=py37_0
  - decorator=4.3.2=py37_0
  - docutils=0.14=py37_0
  - entrypoints=0.3=py37_0
  - freetype=2.9.1=ha9979f8_1
  - hdf5=1.8.20=hac2f561_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - imagesize=1.1.0=py37_0
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - isort=4.3.4=py37_0
  - jedi=0.13.2=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=2.6.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - keyring=17.1.1=py37_0
  - kiwisolver=1.0.1=py37h6538335_0
  - lazy-object-proxy=1.3.1=py37hfa6e2cd_2
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.36=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.0.10=hb898794_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.0=py37he774522_0
  - matplotlib=3.0.2=py37hc8f65d3_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py37h14836fe_0
  - mkl_random=1.0.2=py37h343c172_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - ninja=1.8.2=py37he980bc4_1
  - notebook=5.7.4=py37_0
  - numpy=1.15.4=py37h19fb1c0_0
  - numpy-base=1.15.4=py37hc3f5095_0
  - numpydoc=0.8.0=py37_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h40b0b35_0
  - openssl=1.1.1a=he774522_0
  - packaging=19.0=py37_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.2=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=5.4.1=py37hdc69c19_0
  - pip=19.0.1=py37_0
  - prometheus_client=0.5.0=py37_0
  - prompt_toolkit=2.0.8=py_0
  - psutil=5.5.0=py37he774522_0
  - py-opencv=3.4.2=py37hc319ecb_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.1.0=py37_0
  - pygments=2.3.1=py37_0
  - pylint=2.2.2=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.3.1=py37_0
  - pyqt=5.9.2=py37h6538335_2
  - pysocks=1.6.8=py37_0
  - python=3.7.2=h8c8aaf0_0
  - python-dateutil=2.7.5=py37_0
  - pytorch-cpu=1.0.0=py3.7_cpu_1
  - pytz=2018.9=py37_0
  - pywin32=223=py37hfa6e2cd_1
  - pywinpty=0.5.5=py37_1000
  - pyzmq=17.1.2=py37ha925a31_2
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=0.5.6=py_0
  - qtconsole=4.4.3=py37_0
  - qtpy=1.6.0=py_0
  - requests=2.21.0=py37_0
  - rope=0.11.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=40.7.3=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.12.0=py37_0
  - snowballstemmer=1.2.1=py37_0
  - sphinx=1.8.4=py37_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-websupport=1.1.0=py37_1
  - spyder=3.3.2=py37_0
  - spyder-kernels=0.4.2=py37_0
  - sqlite=3.26.0=he774522_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=hfa6e2cd_0
  - torchvision-cpu=0.2.1=py_2
  - tornado=5.1.1=py37hfa6e2cd_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.1=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - win_inet_pton=1.0.1=py37_1
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.11.1=py37he774522_0
  - xz=5.2.4=h2fa13f4_4
  - zeromq=4.3.1=h33f27b4_3
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - click==7.0
    - dlib==19.16.0
    - face-recognition==1.2.3
    - face-recognition-models==0.3.0


